# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish container image to Quay,GHCR, and Docker Hub

on:
  push:
  
  release:
    types: [published]

jobs:
  push_to_registries:
    name: Push container image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          
      - name: Log in to Quay
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: quay.io/walidshaari
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASS }}          
      
      - name: Log in to the ghcr registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            my-docker-hub-namespace/my-docker-hub-repository
            ghcr.io/${{ github.repository }}
      
      - name: Build and push container images
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            quay.io/walidshaari/python-hello:latest
            quay.io/walidshaari/python-hello:v1.2.0
            wshaari/python-hello-world:latest
            wshaari/python-hello-world:v1.2.0
            ghcr.io/walidshaari/python-helloworld:latest
            ghcr.io/walidshaari/python-helloworld:v1.2.0
            
   
        # tags: ${{ steps.meta.outputs.tags }}
        # labels: ${{ steps.meta.outputs.labels }}
